### PR TITLE
Remove confusing underscore from comments.json filename

### PR DESCRIPTION
**Pull request by mecampbellsoup**
I may be unaware of the reason for having named the comments file `_comments.json`, but I found it very confusing that the URL being requested was set to `comments.json` while the file being read from/written to was in turn named `_comments.json`.

### CODE REVIEW

**Comment by davefp** [comment]
:+1:

**Comment by zpao** [comment]
I just realized I never commented. This is fine by me. The Go server landed since you did this - can you update it as well, then we can merge this.

I originally moved the file to `_comments.json` to make it obvious that while you were accessing `/comments.json` in JS land, you weren't actually reading and writing from the file directly - we only used the file for the initial server start, then just kept updates is memory. That's no longer the case though so it's less important. At this point it might make sense to actually change the server endpoint to `/api/comments` or something (somebody else suggested that a while ago). We can do that separately.

**Comment by zpao** [comment]
Let me know if you're interested in handling to Go server as well, otherwise I can just update that one myself.

**Comment by mecampbellsoup** [comment]
I'll take a look when I get home and reply back.

**Comment by mecampbellsoup** [comment]
@zpao @davefp Changed the Go server reference to `_comments.json` to `comments.json` as well.

**Comment by zpao** [comment]
Looks great. Thanks!

**Comment by mecampbellsoup** [comment]
Thanks guys, happy to contribute (even though it's fairly small)!

**Pull request merged**
