### PR TITLE
Added Algernon/Lua example

### PR DESCRIPTION
**Pull request by xyproto**
* Added instructions in README.md.
* Added `server.lua`.

### CODE REVIEW

**Comment by zpao** [comment]
I like the initiative but this is really much more complicated to use than the other servers. I'm striving for as much consistency as possible.

A few differences from other servers:
- Dependencies: Even when they have dependencies, it's typically `packagemanager install`.
- Running: Everything else is `runtime server.language`, this is start service, copy file from 1 place, edit different file, skip step of tutorial which lets you edit comments.json, no mentioned of index.html.
  - Ideally I'd be able to just run `lua server.lua` as we've made all the others.

Maybe we can have an alternative servers section with instructions and behavior that differ from the others but otherwise this feels out of place as is.

**Comment by xyproto** [comment]
I understand what you are saying, but not all web servers are based on running the web server and the web handlers as one command / process. Both apache and nginx supports a wide range of plugins for various languages, like php, and this is a common way of running php applications.

Running a web server first is not an uncommon starting point. [meteor](https://www.meteor.com/) is a prime example of a way of developing web applications that requires a server to be running first.

If it is a requirement that the web application must be runnable in the form `runtime server.language` it feels like a bit of an arbitrary decision, to me.

When it comes to dependency management, Algernon can be installed on Arch Linux in a single command (`yaourt -S algernon`, for instance) and comes in the form of a single .exe file for Windows. Which package manager are you thinking of where the dependencies would be a problem?

**Comment by xyproto** [comment]
Made a new release of [algernon](https://github.com/xyproto/algernon) where it is now possible to run the script like this:

`algernon server.lua`

Will update the pull request.

**Comment by zpao** [comment]
The point of this repo is to pair as seamlessly as possible with the React tutorial, using whatever command line runtime they have available. It's not really intended to be a place for every solution for every possible server out there. Yes, you can run PHP via Apache and have an `.htaccess` file which says requests to `comments.json` should actually hit a PHP file that reads/writes. Yes, I could have a Ruby on Rails app in here, or a Django app, or use Sinatra, or <insert any server / app runtime>.

It's not a requirement that `runtime server.language` is the only possible way to do the tutorial BUT it is a requirement that it requires virtually zero effort to run a server because I don't want people having to figure that out to learn React. It's also important that all the servers behave the same way so that we can ensure there are no surprises.

As is, that's not the case here. To me this feels more like you're trying to sell Algernon than trying to make it dirt simple for somebody who knows Lua to learn React.

`algernon server.lua` is better, but this still behaves differently than the other servers (as far as I can tell). Redis should not be involved. I would also like to see a simple install instruction as part of the usage.

```sh
# algernon is available on Arch Linux
yaourt -S algernon
algernon server.lua
```

Also, I'd really like to be able to run this server myself so that if we change something, I can try to fix it. I don't see any install instructions for OS X.

**Comment by xyproto** [comment]
I understand. I'll come back to you if Redis is no longer a hard dependency and the installation instructions are clearer. I also want to make it easy for people to get started with React, especially on the server side. Thank you for considering the pull request.

**Pull request closed without merging**
