### PR TITLE
Modified server.js so that Cors is allowed in NodeJS server.

### PR DESCRIPTION
**Pull request by fay-jai**
Currently, when users go through the ReactJS tutorial and reach the part dealing with fetching data from a server, they're not able to successfully run this code block that exists in CommentBox.jsx without running into Cors related issues:

    componentDidMount: function() {
        $.ajax({
            url: this.props.url,
            dataType: 'json',
            cache: false,
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString());
            }.bind(this)
       });
  }

By accepting this change, users going through the tutorial won't face issues when trying to retrieve data from the endpoints set up in server.js.

### CODE REVIEW

**Comment by zpao** [comment]
I haven't seen this reported as being an issue before. Can you describe your case that led to this being an issue? The tutorial as written shouldn't be making cross-origin requests.

**Comment by fay-jai** [comment]
I encountered this when I spun up the server.js file via node and checked out my Chrome browser. I noticed that when my local repo makes an ajax call to "https://localhost:3000/api/comments", my Chrome browser shows the following error message:

"Cannot load http://localhost:3000/api/comments. No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by spicyj** [comment]
Are you loading the tutorial HTML/JS from the same server?

**Comment by fay-jai** [comment]
I'm not serving up my HTML / JS on a server - just running it locally by having the browser load my index.html file (along with the JS). I did spin up a node.js server (which is on localhost:3000)

**Comment by zpao** [comment]
You should be loading <http://localhost:3000/> in your browser (which is served by the node server) *not* the `file://...` URL. I can see the CORS when I load the `file://...` URL.

The readme and the command line output from when running each server should be telling you the right thing here but let me know if there was some other way place we could add some text to make this clearer.

**Pull request closed without merging**
