### PR TITLE
Added server.lua

### PR DESCRIPTION
**Pull request by xyproto**
Simple way to get started with Lua.

* Additional installation instructions for Algernon is available on the Algernon webpage.
* Algernon is reasonably popular.
* There are dependencies on Redis or MySQL. BoltDB is included in Algernon. The only dependency is libreadline, for Linux and OS X (already installed everywhere)
* I'm not selling anything. This is open source software without any connection to a company.

### CODE REVIEW

**Comment by zpao** [comment]
This still doesn't match existing behavior of the tutorial, which reads from and writes to comments.json on every request (allowing it to be edited manually, then having that show up in the browser). Basically comment.json should be considered the database.

**Comment by xyproto** [comment]
The updated Lua script is for Algernon 0.75, and uses the `comments.json` file.

(The current version of Algernon in homebrew is at 0.74, but it will soon be updated).

**Comment by zpao** [comment]
Alright, I got this running. All I can see is the JSON being served. It's supposed to serve the whole tutorial, like all of the other server implementations. Maybe I'm doing something wrong…

**Comment by xyproto** [comment]
Updated `server.lua` to behave exactly like the other samples. Works with the latest version of Algernon which will appear in homebrew shortly.

**Comment by xyproto** [comment]
algernon 0.82 is now available in Homebrew.

**Comment by zpao** [comment]
Thanks for updating. I'm on vacation so will get back to this in ~2 weeks
unless somebody else beats me to it.

**Comment by xyproto** [comment]
Ok. Have a great vacation!

**Comment by zpao** [comment]
One more tweak but I'm going to merge and followup. Thanks!

**Comment by xyproto** [comment]
Thanks for merging!

**Pull request merged**
